// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-y73401QK_eoNtiJ--IBwLLCdt0y1pvk',
    appId: '1:415537858341:web:7a387d06e34cffa23abccc',
    messagingSenderId: '415537858341',
    projectId: 'sde-prep-app',
    authDomain: 'sde-prep-app.firebaseapp.com',
    databaseURL: 'https://sde-prep-app.firebaseio.com',
    storageBucket: 'sde-prep-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-y73401QK_eoNtiJ--IBwLLCdt0y1pvk',
    appId: '1:415537858341:android:7a387d06e34cffa23abccc',
    messagingSenderId: '415537858341',
    projectId: 'sde-prep-app',
    databaseURL: 'https://sde-prep-app.firebaseio.com',
    storageBucket: 'sde-prep-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJJKywfWybgCNRCOM22wJ8EPgkpQcbJUk',
    appId: '1:415537858341:ios:ad33425dca2359193abccc',
    messagingSenderId: '415537858341',
    projectId: 'sde-prep-app',
    databaseURL: 'https://sde-prep-app.firebaseio.com',
    storageBucket: 'sde-prep-app.firebasestorage.app',
    iosBundleId: 'com.example.sdePrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJJKywfWybgCNRCOM22wJ8EPgkpQcbJUk',
    appId: '1:415537858341:macos:ad33425dca2359193abccc',
    messagingSenderId: '415537858341',
    projectId: 'sde-prep-app',
    databaseURL: 'https://sde-prep-app.firebaseio.com',
    storageBucket: 'sde-prep-app.firebasestorage.app',
    iosBundleId: 'com.example.sdePrepMacos',
  );
}
